image: gitlab-registry.cern.ch/matteomi/feroce-rs:latest

stages:
  - docker
  - check
  - build
  - test

build-docker:
  stage: docker
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  rules:
    - changes:
        - ci/Dockerfile
      when: always
    - when: never
  script:
    - >
      /kaniko/executor
      --context $CI_PROJECT_DIR
      --dockerfile ci/Dockerfile
      --destination $CI_REGISTRY_IMAGE:latest
      --cache=true

build-docker-gpu:
  stage: docker
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  rules:
    - changes:
        - ci/Dockerfile.gpu
      when: always
    - when: never
  script:
    - >
      /kaniko/executor
      --context $CI_PROJECT_DIR
      --dockerfile ci/Dockerfile.gpu
      --destination $CI_REGISTRY_IMAGE:gpu
      --cache=true

cache:
  key: cargo-cache
  paths:
    - .cargo/registry/
    - target/

variables:
  CARGO_HOME: ${CI_PROJECT_DIR}/.cargo

# code format
fmt:
  stage: check
  before_script:
    - rustup component add rustfmt
  script:
    - cargo fmt --check

# logic (unused variables, warnings, etc)
clippy:
  stage: check
  allow_failure: true
  before_script:
    - rustup component add clippy
  script:
    - cargo clippy -- -D warnings

build:
  stage: build
  script:
    - cargo build

test:
  stage: test
  script:
    - cargo test

test-rdma:
  stage: test
  tags:
    - roce
  before_script:
      - ibv_devinfo -v
      - rdma link show
  script:
    - cargo test --features rdma-test -- --nocapture

test-gpu:
  stage: test
  image: gitlab-registry.cern.ch/matteomi/feroce-rs:gpu
  tags:
    - roce
  before_script:
    - nvidia-smi
    - ibv_devinfo -v
  script:
    - cargo test --features gpu,rdma-test -- --nocapture