FROM docker.io/nvidia/cuda:12.8.0-devel-ubuntu24.04

  RUN apt-get update && apt-get install -y \
      curl \
      libibverbs-dev \
      rdma-core \
      infiniband-diags \
      ibverbs-utils \
      clang \
      && rm -rf /var/lib/apt/lists/*

  RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain 1.93.0
  ENV PATH="/root/.cargo/bin:${PATH}"